title: "Corso di Laurea in Ingegneria Informatica"

# Pagine statiche per categoria
collections:
  triennale:
    output: true
  magistrale:
    output: true
  erasmus:
    output: true
  organizzazione:
    output: true

exclude: [README.md]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-paginate

sass:
  style: compressed

# Per la lista delle ultime comunicazioni
news-in-home: 5
paginate: 10
paginate_path: "/comunicazioni/page:num/"