title: "Corso di Laurea in Ingegneria Informatica"

# Pagine statiche per categoria
collections:
  laurea:
    output: true
  magistrale:
    output: true
  erasmus:
    output: true
  servizi:
    output: true
  orientamento:
    output: true
  comunicazioni:
    output: true
  contatti:
    output: true

exclude: [README.md, old_website]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-toc

sass:
  style: compressed

# Per la lista delle ultime comunicazioni
news-in-home: 5
paginate_path: "/comunicazioni/page:num/"
paginate: 25



toc:
 min_level: 1
 max_level: 5
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist