title: "Corso di Laurea in Ingegneria Informatica"
url: ""

# Pagine statiche per categoria
collections:
  triennale:
    output: true
  magistrale:
    output: true
  contatti:
    output: true

category-list: [triennale, magistrale, contatti]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

sass:
  style: compressed