title: "Corso di Laurea in Ingegneria Informatica"
url: ""

# Pagine statiche per categoria
collections:
  triennale:
    output: true
  magistrale:
    output: true
  contatti:
    output: true

exclude: [README.md]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-paginate

sass:
  style: compressed

# Per la lista delle ultime comunicazioni
paginate: 5
paginate_path: "/news/page:num/"